@startuml

actor       Клиент      as client
control     "MES API"   as mes
database    Redis       as cache

client -> mes : Запрашивает новый расчет стоимости
mes -> cache : Ищет похожий расчет
cache -> mes : Похожий расчет
mes -> client : Стоимость заказа

client --> mes : Запрашивает новый расчет стоимости
mes --> cache : Ищет похожий расчет
cache --> mes : Расчет по похожей модели не производился
mes --> cache : Отправляет в кеш вычисления по модели
mes --> client : Стоимость заказа

@enduml
